import { NextResponse } from 'next/server';
import { supabase, TABLES } from '@/lib/supabase';
import { calculateSuccessScore } from '@/lib/ai';

export async function POST(request: Request) {
  try {
    const data = await request.json();
    
    // Calculate success score using AI
    const successScore = await calculateSuccessScore({
      ...data,
      id: '', // Will be generated by Supabase
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      status: 'pending',
    });

    // Insert into Supabase
    const { data: startup, error } = await supabase
      .from(TABLES.STARTUPS)
      .insert([
        {
          ...data,
          successScore,
          status: 'pending',
        },
      ])
      .select()
      .single();

    if (error) {
      throw error;
    }

    return NextResponse.json(startup);
  } catch (error) {
    console.error('Error submitting startup:', error);
    return NextResponse.json(
      { error: 'Failed to submit startup' },
      { status: 500 }
    );
  }
} 